CREATE TABLE "panel_role" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "panel_role_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "panel_role_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "panel_role_permission" (
	"role_id" integer NOT NULL,
	"permission" text NOT NULL,
	CONSTRAINT "panel_role_permission_role_id_permission_pk" PRIMARY KEY("role_id","permission")
);
--> statement-breakpoint
CREATE TABLE "panel_session" (
	"session_hash" text PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "panel_user" (
	"username" text PRIMARY KEY NOT NULL,
	"display_name" text,
	"password_hash" text NOT NULL,
	"must_change_password" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"last_login_at" timestamp with time zone,
	"is_system_admin" boolean DEFAULT false NOT NULL,
	"role_id" integer,
	CONSTRAINT "panel_user_admin_has_no_role" CHECK ("panel_user"."is_system_admin" = false OR "panel_user"."role_id" IS NULL)
);
--> statement-breakpoint
CREATE TABLE "panel_user_repo" (
	"username" text NOT NULL,
	"repo_id" integer NOT NULL,
	CONSTRAINT "panel_user_repo_username_repo_id_pk" PRIMARY KEY("username","repo_id")
);
--> statement-breakpoint
CREATE TABLE "review_rule" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "review_rule_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"repo_id" integer NOT NULL,
	"type" text DEFAULT 'rule' NOT NULL,
	"scope" text NOT NULL,
	"statement" text NOT NULL,
	"layer" text NOT NULL,
	"state" text NOT NULL,
	"origin" text NOT NULL,
	"effective_version" integer NOT NULL,
	"retired_version" integer,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "review_rule_type" CHECK ("review_rule"."type" IN ('rule', 'fact')),
	CONSTRAINT "review_rule_state" CHECK ("review_rule"."state" IN ('active', 'retired')),
	CONSTRAINT "review_rule_state_matches_retirement" CHECK (("review_rule"."state" = 'active') = ("review_rule"."retired_version" IS NULL))
);
--> statement-breakpoint
CREATE TABLE "rule_consolidation" (
	"repo_id" integer PRIMARY KEY NOT NULL,
	"model" text NOT NULL,
	"thinking_level" text,
	"trace_task_id" integer,
	"state" text NOT NULL,
	"failure" text,
	"merged" integer,
	"retargeted" integer,
	"proposed" integer,
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone,
	CONSTRAINT "rule_consolidation_state" CHECK ("rule_consolidation"."state" IN ('running', 'failed', 'completed'))
);
--> statement-breakpoint
CREATE TABLE "rule_draft_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rule_draft_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"repo_id" integer NOT NULL,
	"type" text DEFAULT 'rule' NOT NULL,
	"scope" text NOT NULL,
	"statement" text NOT NULL,
	"layer" text NOT NULL,
	"origin" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "rule_draft_item_type" CHECK ("rule_draft_item"."type" IN ('rule', 'fact'))
);
--> statement-breakpoint
CREATE TABLE "rule_exploration" (
	"repo_id" integer PRIMARY KEY NOT NULL,
	"baseline_sha" text NOT NULL,
	"model" text NOT NULL,
	"thinking_level" text,
	"trace_task_id" integer,
	"state" text NOT NULL,
	"failure" text,
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone,
	CONSTRAINT "rule_exploration_state" CHECK ("rule_exploration"."state" IN ('running', 'failed', 'completed'))
);
--> statement-breakpoint
CREATE TABLE "rule_intent" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rule_intent_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"repo_id" integer NOT NULL,
	"text" text NOT NULL,
	"submitted_by" text NOT NULL,
	"target_kind" text NOT NULL,
	"target_id" integer,
	"state" text NOT NULL,
	"failure" text,
	"summary" text,
	"model" text,
	"thinking_level" text,
	"trace_task_id" integer,
	"produced_json" jsonb,
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone,
	CONSTRAINT "rule_intent_target_kind" CHECK ("rule_intent"."target_kind" IN ('none', 'rule', 'proposal', 'draft', 'finding')),
	CONSTRAINT "rule_intent_state" CHECK ("rule_intent"."state" IN ('running', 'failed', 'completed')),
	CONSTRAINT "rule_intent_target_shape" CHECK (("rule_intent"."target_kind" = 'none') = ("rule_intent"."target_id" IS NULL))
);
--> statement-breakpoint
CREATE TABLE "rule_proposal" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rule_proposal_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"repo_id" integer NOT NULL,
	"type" text DEFAULT 'rule' NOT NULL,
	"change" text NOT NULL,
	"target_rule_ids" jsonb DEFAULT '[]' NOT NULL,
	"scope" text NOT NULL,
	"statement" text NOT NULL,
	"layer" text NOT NULL,
	"state" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"decided_at" timestamp with time zone,
	CONSTRAINT "rule_proposal_type" CHECK ("rule_proposal"."type" IN ('rule', 'fact')),
	CONSTRAINT "rule_proposal_change" CHECK ("rule_proposal"."change" IN ('add', 'modify', 'retire', 'merge')),
	CONSTRAINT "rule_proposal_state" CHECK ("rule_proposal"."state" IN ('pending', 'accepted', 'rejected')),
	CONSTRAINT "rule_proposal_pending_undecided" CHECK (("rule_proposal"."state" = 'pending') = ("rule_proposal"."decided_at" IS NULL)),
	CONSTRAINT "rule_proposal_add_has_no_target" CHECK (("rule_proposal"."change" = 'add') = ("rule_proposal"."target_rule_ids" = '[]'::jsonb))
);
--> statement-breakpoint
CREATE TABLE "rule_proposal_source" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "rule_proposal_source_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"proposal_id" integer NOT NULL,
	"origin" text NOT NULL,
	"note" text,
	"evidence" text,
	"finding_id" integer,
	"trace_task_id" integer,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "rule_proposal_source_origin" CHECK ("rule_proposal_source"."origin" IN ('baseline-exploration', 'disposition-feedback', 'knowledge-consolidation',
        'manual-proposal'))
);
--> statement-breakpoint
CREATE TABLE "rule_set_version" (
	"repo_id" integer NOT NULL,
	"version" integer NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "rule_set_version_repo_id_version_pk" PRIMARY KEY("repo_id","version"),
	CONSTRAINT "rule_set_version_positive" CHECK ("rule_set_version"."version" > 0)
);
--> statement-breakpoint
CREATE TABLE "rule_trace" (
	"task_id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "rule_trace_task_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"repo_id" integer NOT NULL,
	"source" text NOT NULL,
	"seq" integer NOT NULL,
	"at" timestamp with time zone NOT NULL,
	"kind" text NOT NULL,
	"payload" jsonb NOT NULL,
	CONSTRAINT "rule_trace_task_id_seq_pk" PRIMARY KEY("task_id","seq"),
	CONSTRAINT "rule_trace_source" CHECK ("rule_trace"."source" IN ('baseline-exploration', 'disposition-feedback', 'knowledge-consolidation',
        'manual-proposal'))
);
--> statement-breakpoint
CREATE TABLE "product" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "product_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "product_knowledge_entry" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_knowledge_entry_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer NOT NULL,
	"kind" text NOT NULL,
	"name" text NOT NULL,
	"body" text NOT NULL,
	"topic" text,
	"avoided" jsonb NOT NULL,
	"options" text,
	"consequences" text,
	"superseded_by" integer,
	"annotations" jsonb NOT NULL,
	"written_at" timestamp with time zone NOT NULL,
	"written_by_session_id" integer,
	CONSTRAINT "product_knowledge_entry_kind" CHECK ("product_knowledge_entry"."kind" IN ('term', 'relationship', 'decision'))
);
--> statement-breakpoint
CREATE TABLE "product_repo" (
	"repo_id" integer PRIMARY KEY NOT NULL,
	"product_id" integer NOT NULL,
	"added_at" timestamp with time zone NOT NULL,
	"role" text
);
--> statement-breakpoint
CREATE TABLE "product_spec" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_spec_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"state" text NOT NULL,
	"session_id" integer,
	"created_at" timestamp with time zone NOT NULL,
	"state_changed_at" timestamp with time zone NOT NULL,
	CONSTRAINT "product_spec_state" CHECK ("product_spec"."state" IN ('open', 'closed'))
);
--> statement-breakpoint
CREATE TABLE "product_ticket" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_ticket_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"spec_id" integer NOT NULL,
	"title" text NOT NULL,
	"body" text NOT NULL,
	"label" text NOT NULL,
	"state" text NOT NULL,
	"claimed_by" text,
	"session_id" integer,
	"created_at" timestamp with time zone NOT NULL,
	"state_changed_at" timestamp with time zone NOT NULL,
	CONSTRAINT "product_ticket_label" CHECK ("product_ticket"."label" IN ('needs-triage', 'needs-info', 'ready-for-agent', 'ready-for-human',
        'wontfix')),
	CONSTRAINT "product_ticket_state" CHECK ("product_ticket"."state" IN ('open', 'closed'))
);
--> statement-breakpoint
CREATE TABLE "product_ticket_block" (
	"ticket_id" integer NOT NULL,
	"blocked_by_id" integer NOT NULL,
	CONSTRAINT "product_ticket_block_ticket_id_blocked_by_id_pk" PRIMARY KEY("ticket_id","blocked_by_id"),
	CONSTRAINT "product_ticket_block_not_self" CHECK ("product_ticket_block"."ticket_id" <> "product_ticket_block"."blocked_by_id")
);
--> statement-breakpoint
CREATE TABLE "product_ticket_comment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "product_ticket_comment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ticket_id" integer NOT NULL,
	"author" text,
	"session_id" integer,
	"body" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "global_setting" (
	"key" text PRIMARY KEY NOT NULL,
	"value" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "model_directory" (
	"provider" text PRIMARY KEY NOT NULL,
	"service_version" integer NOT NULL,
	"state" text NOT NULL,
	"last_attempt_at" timestamp with time zone,
	"last_success_at" timestamp with time zone,
	"failure" text,
	"ignored_model_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "model_directory_service_version_positive" CHECK ("model_directory"."service_version" > 0),
	CONSTRAINT "model_directory_state" CHECK ("model_directory"."state" IN ('undiscovered', 'available', 'refresh-failed', 'discovery-failed')),
	CONSTRAINT "model_directory_ignored_model_count" CHECK ("model_directory"."ignored_model_count" >= 0),
	CONSTRAINT "model_directory_shape" CHECK (("model_directory"."state" = 'undiscovered' AND "model_directory"."last_attempt_at" IS NULL
        AND "model_directory"."last_success_at" IS NULL AND "model_directory"."failure" IS NULL AND "model_directory"."ignored_model_count" = 0)
      OR ("model_directory"."state" = 'available' AND "model_directory"."last_attempt_at" IS NOT NULL
        AND "model_directory"."last_success_at" IS NOT NULL AND "model_directory"."failure" IS NULL)
      OR ("model_directory"."state" = 'refresh-failed' AND "model_directory"."last_attempt_at" IS NOT NULL
        AND "model_directory"."last_success_at" IS NOT NULL AND "model_directory"."failure" IS NOT NULL)
      OR ("model_directory"."state" = 'discovery-failed' AND "model_directory"."last_attempt_at" IS NOT NULL
        AND "model_directory"."last_success_at" IS NULL AND "model_directory"."failure" IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "model_directory_model" (
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"service_version" integer NOT NULL,
	"name" text,
	"api" text,
	"base_url" text,
	"input_json" jsonb,
	"reasoning" boolean,
	"context_window" integer,
	"max_tokens" integer,
	"field_sources_json" jsonb,
	"thinking_level_map_json" jsonb,
	"compat_json" jsonb,
	CONSTRAINT "model_directory_model_provider_model_pk" PRIMARY KEY("provider","model"),
	CONSTRAINT "model_directory_model_not_empty" CHECK ("model_directory_model"."model" <> ''),
	CONSTRAINT "model_directory_model_service_version_positive" CHECK ("model_directory_model"."service_version" > 0)
);
--> statement-breakpoint
CREATE TABLE "model_service" (
	"provider" text PRIMARY KEY NOT NULL,
	"service_type" text NOT NULL,
	"version" integer NOT NULL,
	"base_url" text,
	"api" text,
	"target_fingerprint" text,
	"disabled_reason" text,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"targets_json" jsonb,
	CONSTRAINT "model_service_type" CHECK ("model_service"."service_type" IN ('builtin', 'custom')),
	CONSTRAINT "model_service_version_positive" CHECK ("model_service"."version" > 0),
	CONSTRAINT "model_service_disabled_reason" CHECK ("model_service"."disabled_reason" IS NULL OR "model_service"."disabled_reason" = 'name-conflict'),
	CONSTRAINT "model_service_target_shape" CHECK (("model_service"."service_type" = 'custom' AND "model_service"."base_url" IS NOT NULL AND "model_service"."api" IS NOT NULL
        AND "model_service"."target_fingerprint" IS NOT NULL)
      OR ("model_service"."service_type" = 'builtin' AND "model_service"."base_url" IS NULL AND "model_service"."api" IS NULL))
);
--> statement-breakpoint
CREATE TABLE "model_service_credential" (
	"provider" text PRIMARY KEY NOT NULL,
	"state" text NOT NULL,
	"api_key_encrypted" text,
	"updated_at" timestamp with time zone,
	"verified_at" timestamp with time zone,
	"validation_model" text,
	"verification_source" text,
	CONSTRAINT "model_service_credential_state" CHECK ("model_service_credential"."state" IN ('unconfigured', 'pending-reverification', 'verified')),
	CONSTRAINT "model_service_credential_verification_source" CHECK ("model_service_credential"."verification_source" IS NULL OR "model_service_credential"."verification_source" IN (
        'legacy-provider-check', 'legacy-review-run', 'inference'
      )),
	CONSTRAINT "model_service_credential_shape" CHECK (("model_service_credential"."state" = 'unconfigured' AND "model_service_credential"."api_key_encrypted" IS NULL AND "model_service_credential"."updated_at" IS NULL
        AND "model_service_credential"."verified_at" IS NULL AND "model_service_credential"."validation_model" IS NULL
        AND "model_service_credential"."verification_source" IS NULL)
      OR ("model_service_credential"."state" = 'pending-reverification' AND "model_service_credential"."api_key_encrypted" IS NOT NULL
        AND "model_service_credential"."updated_at" IS NOT NULL AND "model_service_credential"."verified_at" IS NULL
        AND "model_service_credential"."validation_model" IS NULL AND "model_service_credential"."verification_source" IS NULL)
      OR ("model_service_credential"."state" = 'verified' AND "model_service_credential"."api_key_encrypted" IS NOT NULL
        AND "model_service_credential"."updated_at" IS NOT NULL AND "model_service_credential"."verified_at" IS NOT NULL
        AND "model_service_credential"."verification_source" IS NOT NULL))
);
--> statement-breakpoint
CREATE TABLE "model_service_model_state" (
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"enabled" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	CONSTRAINT "model_service_model_state_provider_model_pk" PRIMARY KEY("provider","model"),
	CONSTRAINT "model_service_model_state_model_not_empty" CHECK ("model_service_model_state"."model" <> '')
);
--> statement-breakpoint
CREATE TABLE "model_supplement" (
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"source" text NOT NULL,
	"target_fingerprint" text,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "model_supplement_provider_model_pk" PRIMARY KEY("provider","model"),
	CONSTRAINT "model_supplement_model_not_empty" CHECK ("model_supplement"."model" <> ''),
	CONSTRAINT "model_supplement_source" CHECK ("model_supplement"."source" IN ('manual', 'migration-retention')),
	CONSTRAINT "model_supplement_shape" CHECK (("model_supplement"."source" = 'manual' AND "model_supplement"."target_fingerprint" IS NOT NULL)
      OR ("model_supplement"."source" = 'migration-retention' AND "model_supplement"."target_fingerprint" IS NULL))
);
--> statement-breakpoint
CREATE TABLE "repo" (
	"id" integer PRIMARY KEY NOT NULL,
	"owner" text NOT NULL,
	"repo" text NOT NULL,
	"reviewers" text,
	"worktree_state" text,
	"worktree_failure" text,
	"worktree_checked_at" timestamp with time zone,
	"registered_at" timestamp with time zone NOT NULL,
	"auxiliary_model" text,
	"min_report_severity" text,
	"default_branch" text,
	"settings_version" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "repo_key" (
	"repo_id" integer NOT NULL,
	"generation" integer NOT NULL,
	"key" text NOT NULL,
	CONSTRAINT "repo_key_repo_id_generation_pk" PRIMARY KEY("repo_id","generation")
);
--> statement-breakpoint
CREATE TABLE "webhook_delivery" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "webhook_delivery_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner" text NOT NULL,
	"repo" text NOT NULL,
	"head_sha" text NOT NULL,
	"claimed_at" timestamp with time zone NOT NULL,
	CONSTRAINT "webhook_delivery_owner_repo_head_sha_key" UNIQUE("owner","repo","head_sha")
);
--> statement-breakpoint
CREATE TABLE "finding" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "finding_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_id" integer NOT NULL,
	"file" text NOT NULL,
	"line" integer NOT NULL,
	"severity" text NOT NULL,
	"category" text NOT NULL,
	"title" text,
	"description" text NOT NULL,
	"impact" text,
	"suggestion" text,
	"fingerprint" text,
	"group_index" integer NOT NULL,
	"disposition" text DEFAULT 'unknown' NOT NULL,
	"placement" text DEFAULT 'inline' NOT NULL,
	"comment_id" text,
	"comment_html_url" text,
	"disposed_by" text,
	"disposed_at" timestamp with time zone,
	"disposition_note" text,
	"continued_from" text,
	"handoff_pending" boolean,
	"line_author_sha" text,
	"line_author_name" text,
	"line_author_email" text,
	"line_author_at" timestamp with time zone,
	"line_author_adjacent" boolean,
	"rule_id" integer,
	"placed_line" integer,
	"placed_run_id" integer
);
--> statement-breakpoint
CREATE TABLE "finding_attribution" (
	"finding_id" integer NOT NULL,
	"position" integer NOT NULL,
	"model" text NOT NULL,
	"severity" text NOT NULL,
	"category" text NOT NULL,
	"description" text NOT NULL,
	"impact" text,
	"suggestion" text,
	CONSTRAINT "finding_attribution_finding_id_position_pk" PRIMARY KEY("finding_id","position")
);
--> statement-breakpoint
CREATE TABLE "finding_carried_attribution" (
	"finding_id" integer NOT NULL,
	"position" integer NOT NULL,
	"model" text NOT NULL,
	"run_id" integer NOT NULL,
	"description" text NOT NULL,
	"impact" text,
	"suggestion" text,
	CONSTRAINT "finding_carried_attribution_finding_id_position_pk" PRIMARY KEY("finding_id","position")
);
--> statement-breakpoint
CREATE TABLE "finding_verdict" (
	"run_id" integer NOT NULL,
	"model" text NOT NULL,
	"finding_id" integer NOT NULL,
	"verdict" text NOT NULL,
	"missing" boolean DEFAULT false NOT NULL,
	"missing_reason" text,
	CONSTRAINT "finding_verdict_run_id_model_finding_id_pk" PRIMARY KEY("run_id","model","finding_id")
);
--> statement-breakpoint
CREATE TABLE "review_run" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "review_run_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"owner" text NOT NULL,
	"repo" text NOT NULL,
	"pull_number" integer NOT NULL,
	"head_sha" text NOT NULL,
	"title" text,
	"range_review_id" integer,
	"pr_state" text,
	"triggered_by" text,
	"trigger_source" text,
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone,
	"duration_ms" integer,
	"changed_files" integer NOT NULL,
	"changed_lines" integer NOT NULL,
	"batch_count" integer NOT NULL,
	"failed" boolean,
	"input_tokens" integer,
	"output_tokens" integer,
	"cache_read_tokens" integer,
	"cache_write_tokens" integer,
	"total_tokens" integer,
	"rule_set_version" integer,
	"directive" text,
	"mode" text,
	"history_json" jsonb,
	"failure" text,
	"batch_plan_json" jsonb,
	"min_report_severity" text,
	"auxiliary_model" jsonb
);
--> statement-breakpoint
CREATE TABLE "review_run_batch_outcome" (
	"run_id" integer NOT NULL,
	"batch_index" integer NOT NULL,
	"model" text NOT NULL,
	"outcome_json" jsonb NOT NULL,
	CONSTRAINT "review_run_batch_outcome_run_id_batch_index_model_pk" PRIMARY KEY("run_id","batch_index","model")
);
--> statement-breakpoint
CREATE TABLE "review_run_reviewer_pin" (
	"run_id" integer NOT NULL,
	"position" integer NOT NULL,
	"identity" text NOT NULL,
	"provider" text NOT NULL,
	"model" text NOT NULL,
	"model_service_version" integer,
	"base_url" text,
	"api" text,
	"runtime_model_json" jsonb,
	"materialization_failure" text,
	"thinking_level" text,
	CONSTRAINT "review_run_reviewer_pin_run_id_position_pk" PRIMARY KEY("run_id","position"),
	CONSTRAINT "review_run_reviewer_pin_run_id_identity_key" UNIQUE("run_id","identity")
);
--> statement-breakpoint
CREATE TABLE "review_trace" (
	"run_id" integer NOT NULL,
	"seq" integer NOT NULL,
	"at" timestamp with time zone NOT NULL,
	"scope" text NOT NULL,
	"reviewer" text,
	"kind" text NOT NULL,
	"payload" jsonb NOT NULL,
	CONSTRAINT "review_trace_run_id_seq_pk" PRIMARY KEY("run_id","seq")
);
--> statement-breakpoint
CREATE TABLE "reviewer_outcome" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reviewer_outcome_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_id" integer NOT NULL,
	"model" text NOT NULL,
	"failure" text,
	"finding_count" integer NOT NULL,
	"anomaly_count" integer NOT NULL,
	"rejected_tool_calls" integer NOT NULL,
	"anchor_rejections" integer DEFAULT 0 NOT NULL,
	"duration_ms" integer NOT NULL,
	"input_tokens" integer,
	"output_tokens" integer,
	"cache_read_tokens" integer,
	"cache_write_tokens" integer,
	"total_tokens" integer
);
--> statement-breakpoint
CREATE TABLE "root_cause_group" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "root_cause_group_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_id" integer NOT NULL,
	"reason" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "root_cause_group_member" (
	"group_id" integer NOT NULL,
	"finding_id" integer NOT NULL,
	"position" integer NOT NULL,
	CONSTRAINT "root_cause_group_member_group_id_finding_id_pk" PRIMARY KEY("group_id","finding_id")
);
--> statement-breakpoint
CREATE TABLE "agent_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "agent_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"product_id" integer NOT NULL,
	"created_by" text NOT NULL,
	"purpose" text NOT NULL,
	"status" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"input_tokens" integer DEFAULT 0 NOT NULL,
	"output_tokens" integer DEFAULT 0 NOT NULL,
	"cache_read_tokens" integer DEFAULT 0 NOT NULL,
	"cache_write_tokens" integer DEFAULT 0 NOT NULL,
	"total_tokens" integer DEFAULT 0 NOT NULL,
	"baselines" jsonb,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "agent_session_entry" (
	"session_id" integer NOT NULL,
	"seq" integer NOT NULL,
	"type" text NOT NULL,
	"at" timestamp with time zone NOT NULL,
	"entry" jsonb NOT NULL,
	"input_tokens" integer DEFAULT 0 NOT NULL,
	"output_tokens" integer DEFAULT 0 NOT NULL,
	"cache_read_tokens" integer DEFAULT 0 NOT NULL,
	"cache_write_tokens" integer DEFAULT 0 NOT NULL,
	"total_tokens" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "agent_session_entry_session_id_seq_pk" PRIMARY KEY("session_id","seq")
);
--> statement-breakpoint
CREATE TABLE "agent_session_image" (
	"session_id" integer NOT NULL,
	"image_id" text NOT NULL,
	"path" text NOT NULL,
	"mime_type" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	CONSTRAINT "agent_session_image_session_id_image_id_pk" PRIMARY KEY("session_id","image_id")
);
--> statement-breakpoint
CREATE TABLE "agent_session_message" (
	"session_id" integer NOT NULL,
	"client_message_id" text NOT NULL,
	"accepted_at" timestamp with time zone NOT NULL,
	CONSTRAINT "agent_session_message_session_id_client_message_id_pk" PRIMARY KEY("session_id","client_message_id")
);
--> statement-breakpoint
CREATE TABLE "agent_session_pending_message" (
	"session_id" integer NOT NULL,
	"seq" integer NOT NULL,
	"mode" text NOT NULL,
	"text" text NOT NULL,
	"images" jsonb,
	CONSTRAINT "agent_session_pending_message_session_id_seq_pk" PRIMARY KEY("session_id","seq")
);
--> statement-breakpoint
CREATE TABLE "range_review" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "range_review_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"repo_id" integer NOT NULL,
	"owner" text NOT NULL,
	"repo" text NOT NULL,
	"title" text,
	"base_sha" text NOT NULL,
	"comparison_sha" text NOT NULL,
	"comparison_source_kind" text,
	"comparison_source_name" text,
	"state" text NOT NULL,
	"container_pull_number" integer,
	"base_branch" text NOT NULL,
	"head_branch" text NOT NULL,
	"created_by" text NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"completed_by" text,
	"completed_at" timestamp with time zone,
	"last_forge_failure" text,
	"daily_increment_enabled" boolean DEFAULT false NOT NULL,
	"daily_increment_branch" text,
	"daily_increment_enabled_at" timestamp with time zone,
	"scheduled_check_at" timestamp with time zone,
	"scheduled_check_result" text,
	"scheduled_check_time" text DEFAULT '00:00' NOT NULL,
	"scheduled_check_mode" text DEFAULT 'verdict-only' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "range_review_comparison" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "range_review_comparison_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"range_review_id" integer NOT NULL,
	"sha" text NOT NULL,
	"recorded_by" text NOT NULL,
	"recorded_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "panel_role_permission" ADD CONSTRAINT "panel_role_permission_role_id_panel_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."panel_role"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "panel_session" ADD CONSTRAINT "panel_session_username_panel_user_username_fk" FOREIGN KEY ("username") REFERENCES "public"."panel_user"("username") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "panel_user" ADD CONSTRAINT "panel_user_role_id_panel_role_id_fk" FOREIGN KEY ("role_id") REFERENCES "public"."panel_role"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "panel_user_repo" ADD CONSTRAINT "panel_user_repo_username_panel_user_username_fk" FOREIGN KEY ("username") REFERENCES "public"."panel_user"("username") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "panel_user_repo" ADD CONSTRAINT "panel_user_repo_repo_id_repo_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_rule" ADD CONSTRAINT "review_rule_repo_id_repo_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rule_consolidation" ADD CONSTRAINT "rule_consolidation_repo_id_repo_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rule_draft_item" ADD CONSTRAINT "rule_draft_item_repo_id_repo_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rule_exploration" ADD CONSTRAINT "rule_exploration_repo_id_repo_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rule_intent" ADD CONSTRAINT "rule_intent_repo_id_repo_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rule_proposal" ADD CONSTRAINT "rule_proposal_repo_id_repo_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rule_proposal_source" ADD CONSTRAINT "rule_proposal_source_proposal_id_rule_proposal_id_fk" FOREIGN KEY ("proposal_id") REFERENCES "public"."rule_proposal"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rule_set_version" ADD CONSTRAINT "rule_set_version_repo_id_repo_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "rule_trace" ADD CONSTRAINT "rule_trace_repo_id_repo_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_knowledge_entry" ADD CONSTRAINT "product_knowledge_entry_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_knowledge_entry" ADD CONSTRAINT "product_knowledge_entry_superseded_by_product_knowledge_entry_id_fk" FOREIGN KEY ("superseded_by") REFERENCES "public"."product_knowledge_entry"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_repo" ADD CONSTRAINT "product_repo_repo_id_repo_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_repo" ADD CONSTRAINT "product_repo_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_spec" ADD CONSTRAINT "product_spec_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_ticket" ADD CONSTRAINT "product_ticket_spec_id_product_spec_id_fk" FOREIGN KEY ("spec_id") REFERENCES "public"."product_spec"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_ticket_block" ADD CONSTRAINT "product_ticket_block_ticket_id_product_ticket_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."product_ticket"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_ticket_block" ADD CONSTRAINT "product_ticket_block_blocked_by_id_product_ticket_id_fk" FOREIGN KEY ("blocked_by_id") REFERENCES "public"."product_ticket"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "product_ticket_comment" ADD CONSTRAINT "product_ticket_comment_ticket_id_product_ticket_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."product_ticket"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "repo_key" ADD CONSTRAINT "repo_key_repo_id_repo_id_fk" FOREIGN KEY ("repo_id") REFERENCES "public"."repo"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finding" ADD CONSTRAINT "finding_run_id_review_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."review_run"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finding" ADD CONSTRAINT "finding_placed_run_id_review_run_id_fk" FOREIGN KEY ("placed_run_id") REFERENCES "public"."review_run"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finding_attribution" ADD CONSTRAINT "finding_attribution_finding_id_finding_id_fk" FOREIGN KEY ("finding_id") REFERENCES "public"."finding"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finding_carried_attribution" ADD CONSTRAINT "finding_carried_attribution_finding_id_finding_id_fk" FOREIGN KEY ("finding_id") REFERENCES "public"."finding"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finding_carried_attribution" ADD CONSTRAINT "finding_carried_attribution_run_id_review_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."review_run"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finding_verdict" ADD CONSTRAINT "finding_verdict_run_id_review_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."review_run"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "finding_verdict" ADD CONSTRAINT "finding_verdict_finding_id_finding_id_fk" FOREIGN KEY ("finding_id") REFERENCES "public"."finding"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_run_batch_outcome" ADD CONSTRAINT "review_run_batch_outcome_run_id_review_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."review_run"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_run_reviewer_pin" ADD CONSTRAINT "review_run_reviewer_pin_run_id_review_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."review_run"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "review_trace" ADD CONSTRAINT "review_trace_run_id_review_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."review_run"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reviewer_outcome" ADD CONSTRAINT "reviewer_outcome_run_id_review_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."review_run"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "root_cause_group" ADD CONSTRAINT "root_cause_group_run_id_review_run_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."review_run"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "root_cause_group_member" ADD CONSTRAINT "root_cause_group_member_group_id_root_cause_group_id_fk" FOREIGN KEY ("group_id") REFERENCES "public"."root_cause_group"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "root_cause_group_member" ADD CONSTRAINT "root_cause_group_member_finding_id_finding_id_fk" FOREIGN KEY ("finding_id") REFERENCES "public"."finding"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_session" ADD CONSTRAINT "agent_session_product_id_product_id_fk" FOREIGN KEY ("product_id") REFERENCES "public"."product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_session_entry" ADD CONSTRAINT "agent_session_entry_session_id_agent_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."agent_session"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_session_image" ADD CONSTRAINT "agent_session_image_session_id_agent_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."agent_session"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_session_message" ADD CONSTRAINT "agent_session_message_session_id_agent_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."agent_session"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "agent_session_pending_message" ADD CONSTRAINT "agent_session_pending_message_session_id_agent_session_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."agent_session"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "panel_session_by_user" ON "panel_session" USING btree ("username");--> statement-breakpoint
CREATE INDEX "review_rule_by_repo" ON "review_rule" USING btree ("repo_id");--> statement-breakpoint
CREATE INDEX "rule_draft_item_by_repo" ON "rule_draft_item" USING btree ("repo_id");--> statement-breakpoint
CREATE INDEX "rule_intent_by_repo" ON "rule_intent" USING btree ("repo_id");--> statement-breakpoint
CREATE INDEX "rule_proposal_by_repo" ON "rule_proposal" USING btree ("repo_id");--> statement-breakpoint
CREATE INDEX "rule_proposal_source_by_proposal" ON "rule_proposal_source" USING btree ("proposal_id");--> statement-breakpoint
CREATE INDEX "rule_trace_by_repo" ON "rule_trace" USING btree ("repo_id");--> statement-breakpoint
CREATE INDEX "product_knowledge_entry_by_product" ON "product_knowledge_entry" USING btree ("product_id","kind");--> statement-breakpoint
CREATE UNIQUE INDEX "product_knowledge_entry_by_name" ON "product_knowledge_entry" USING btree ("product_id","kind","name") WHERE "product_knowledge_entry"."name" <> '';--> statement-breakpoint
CREATE INDEX "product_repo_by_product" ON "product_repo" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "product_spec_by_product" ON "product_spec" USING btree ("product_id");--> statement-breakpoint
CREATE INDEX "product_ticket_by_spec" ON "product_ticket" USING btree ("spec_id");--> statement-breakpoint
CREATE INDEX "product_ticket_comment_by_ticket" ON "product_ticket_comment" USING btree ("ticket_id");--> statement-breakpoint
CREATE INDEX "finding_by_run" ON "finding" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "finding_by_anchor" ON "finding" USING btree ("file","fingerprint");--> statement-breakpoint
CREATE INDEX "finding_attribution_by_model" ON "finding_attribution" USING btree ("model");--> statement-breakpoint
CREATE INDEX "review_run_by_pr" ON "review_run" USING btree ("owner","repo","pull_number");--> statement-breakpoint
CREATE INDEX "review_run_by_range" ON "review_run" USING btree ("range_review_id");--> statement-breakpoint
CREATE INDEX "root_cause_group_by_run" ON "root_cause_group" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX "agent_session_by_product" ON "agent_session" USING btree ("product_id","created_by");--> statement-breakpoint
CREATE INDEX "range_review_by_base" ON "range_review" USING btree ("owner","repo","base_sha");--> statement-breakpoint
CREATE INDEX "range_review_comparison_by_review" ON "range_review_comparison" USING btree ("range_review_id");