#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# 在**跑服务的那台服务器**上执行。服务器上不需要源码,只要这些文件放在同一个目录:
#
#   docker-compose.yml         本仓库根目录那一份,拷过来
#   setup.sh                   本脚本
#   .env                       由本脚本生成
#   multireviewer.config.json  由本脚本生成
#   data/                      由本脚本创建,SQLite 与工作副本缓存落在这里
#
# 镜像在开发机上构建后推到 registry(`scripts/build-push.sh`),这里只负责拉取。
# 你从笔记本 SSH 进来,浏览器留在笔记本上——脚本给出的网址在笔记本上打开,把值粘回来。
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# 脚本自己所在的目录就是部署目录。在仓库里直接跑时它在 scripts/ 下,compose 文件在
# 上一级,这里一并认掉。
DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -f "$DEPLOY_DIR/docker-compose.yml" ]] || DEPLOY_DIR="$(dirname "$DEPLOY_DIR")"
cd "$DEPLOY_DIR"
ENV_FILE="$DEPLOY_DIR/.env"

# compose 以「只读单文件」的方式绑定 multireviewer.config.json。绑定发生时宿主机上这
# 个路径不存在的话,docker 会替你建一个同名目录、属主是 root,此后写配置就撞上
# "Is a directory",而且没有 sudo 清不掉。第一条 compose 命令跑起来之前先坐实它是
# 文件——数据目录那一步的探针就已经会起容器,那时配置还没写。
if [[ -d multireviewer.config.json ]]; then
  printf '\n  %s✗ multireviewer.config.json 是个目录,不是文件%s\n\n' "$RED" "$RESET"
  printf '  这是上一次运行留下的残骸。清掉再重跑:\n\n'
  printf '      %ssudo rm -rf %s/multireviewer.config.json%s\n\n' \
    "$BOLD" "$DEPLOY_DIR" "$RESET"
  exit 1
fi
[[ -f multireviewer.config.json ]] || : > multireviewer.config.json

# 某个阶段要产出的值已经全在 .env 里时跳过它,重跑向导因此只补没做完的部分。
# FORCE=1 强制每个阶段都重做。
have_all() {
  if [[ -n "${FORCE:-}" ]]; then return 1; fi
  local key
  for key in "$@"; do
    [[ -n "$(_existing "$key" || true)" ]] || return 1
  done
  return 0
}

skipped_stage() {
  note "已配置,跳过。要重做就 FORCE=1 重跑本脚本。"
}

banner "MultiReviewer 部署"

# ── 1. 前置检查与镜像 ─────────────────────────────────────────────────────
stage "前置检查与镜像"

for cmd in docker curl openssl; do
  if command -v "$cmd" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$cmd"
  else
    printf '  %s✗ 缺少 %s%s\n' "$RED" "$cmd" "$RESET"; exit 1
  fi
done

if docker compose version >/dev/null 2>&1; then
  printf '  %s✓%s docker compose\n' "$GREEN" "$RESET"
else
  printf '  %s✗ 没有 docker compose 插件%s\n' "$RED" "$RESET"
  say "本脚本用的是 docker compose(v2 插件),不是独立的 docker-compose 命令。"
  exit 1
fi

if [[ ! -f docker-compose.yml ]]; then
  printf '  %s✗ 当前目录没有 docker-compose.yml%s\n' "$RED" "$RESET"
  say "把仓库根目录的 docker-compose.yml 与本脚本放到同一个目录再跑。"
  exit 1
fi
printf '  %s✓%s docker-compose.yml\n' "$GREEN" "$RESET"
note "部署目录 $DEPLOY_DIR"

say ""
say "镜像在开发机上构建并推到 registry:"
printf '      %sscripts/build-push.sh <镜像引用>%s\n' "$BOLD" "$RESET"
note "开发机是 arm64、服务器是 amd64 时,构建必须带 --platform linux/amd64,"
note "上面那个脚本已经默认这么做了。架构不对时容器起不来,报 exec format error。"

ask MULTIREVIEWER_IMAGE "镜像引用(如 registry.example.com/team/multireviewer:latest):"
write_env MULTIREVIEWER_IMAGE "$MULTIREVIEWER_IMAGE"

say "拉镜像。registry 需要登录时先 Ctrl-C,docker login 之后重跑。"
if docker compose pull; then
  printf '  %s✓%s 镜像已拉到本地\n' "$GREEN" "$RESET"
else
  printf '  %s✗ 拉取失败%s\n' "$RED" "$RESET"
  say "查:镜像引用是否拼对、是否已 docker login、镜像是否真的推上去了。"
  exit 1
fi
pause

# ── 2. 数据目录 ───────────────────────────────────────────────────────────
stage "数据目录"
say "SQLite 与工作副本缓存落在 $DEPLOY_DIR/data,绑进容器的 /data。"
note "工作副本是每个仓库一份完整 clone,磁盘占用看仓库大小。"

mkdir -p data

# 容器以当前这个宿主机用户的身份运行,新建的 data 目录天然归它所有,不必 chown。
# 部署目录在 home 下时这一点尤其重要:把它改成别的属主会让你写不进自己的 home。
MULTIREVIEWER_UID=$(id -u)
MULTIREVIEWER_GID=$(id -g)
write_env MULTIREVIEWER_UID "$MULTIREVIEWER_UID"
write_env MULTIREVIEWER_GID "$MULTIREVIEWER_GID"
note "容器将以 ${MULTIREVIEWER_UID}:${MULTIREVIEWER_GID} 运行。"

say "拿容器自己验一次这个目录写得进去。"
if docker compose run --rm -T --entrypoint sh multireviewer \
     -c 'touch /data/.probe && rm /data/.probe' >/dev/null 2>&1; then
  printf '  %s✓%s 容器写得进 /data\n' "$GREEN" "$RESET"
else
  printf '  %s✗ 容器写不进 /data%s\n' "$RED" "$RESET"
  say "多半是 $DEPLOY_DIR/data 归别人所有。执行:"
  printf '      %ssudo chown -R %s:%s %s/data%s\n' \
    "$BOLD" "$MULTIREVIEWER_UID" "$MULTIREVIEWER_GID" "$DEPLOY_DIR" "$RESET"
  exit 1
fi
pause

# ── 3. Gitea 实例与 bot 凭据 ──────────────────────────────────────────────
stage "Gitea 实例与 bot 凭据"
if have_all MULTIREVIEWER_GITEA_URL MULTIREVIEWER_GITEA_TOKEN; then
  MULTIREVIEWER_GITEA_URL=$(_existing MULTIREVIEWER_GITEA_URL)
  MULTIREVIEWER_GITEA_TOKEN=$(_existing MULTIREVIEWER_GITEA_TOKEN)
  note "凭据已配置,只做连通与版本核对。要重填就 FORCE=1 重跑。"
else
  say "审查评论以一个专用 bot 账号的身份发出。它需要:"
  step "一枚该账号签发的 PAT,scope 只勾 write:repository(实测确认的最小集合)。"
  step "该账号以协作者身份加入每一个要审查的仓库——Gitea 的 PAT scope 不限定到具体"
  say "  仓库,能访问哪些仓库完全取决于这一步。"
  note "两件事都做完了再往下。签发页在 <实例地址>/user/settings/applications"

  ask        MULTIREVIEWER_GITEA_URL   "Gitea 实例根地址(如 https://gitea.example.com):"
  ask_secret MULTIREVIEWER_GITEA_TOKEN "粘贴 bot 账号的 PAT:"
  write_env  MULTIREVIEWER_GITEA_URL   "$MULTIREVIEWER_GITEA_URL"
  write_env  MULTIREVIEWER_GITEA_TOKEN "$MULTIREVIEWER_GITEA_TOKEN"
fi

say "拿这枚凭据读一次实例版本,当场验证地址与令牌。"
GITEA_VERSION=$(curl -sS -f \
  -H "Authorization: token ${MULTIREVIEWER_GITEA_TOKEN}" \
  "${MULTIREVIEWER_GITEA_URL%/}/api/v1/version" \
  | sed -E 's/.*"version" *: *"([^"]+)".*/\1/') || GITEA_VERSION=""

if [[ -z "$GITEA_VERSION" ]]; then
  printf '  %s✗ 读不到版本%s\n' "$RED" "$RESET"
  say "地址不对、令牌无效、或实例不允许这枚令牌调用 API。三者都查一遍再重跑。"
  say "这台服务器也可能根本访问不到 Gitea——先 curl 一下实例地址确认网络通。"
  exit 1
fi
printf '  %s✓%s 实例版本 %s\n' "$GREEN" "$RESET" "$GITEA_VERSION"
note "下限:社区版 1.26.0 / 企业版 26.0.0。Disposition 依赖的 resolve 端点自该版本才有。"
note "服务启动时会再检查一次,不合格会直接退出。"
pause

# ── 4. DeepSeek 密钥 ──────────────────────────────────────────────────────
stage "DeepSeek 密钥"
if have_all DEEPSEEK_API_KEY; then
  skipped_stage
else
  say "第一个 Reviewer 走 DeepSeek 官方接口。"
  open_url "https://platform.deepseek.com/api_keys"
  step "登录后进 API keys 页,点「创建 API key」。"
  step "密钥只在创建那一刻完整显示一次,当场复制。"
  ask_secret DEEPSEEK_API_KEY "粘贴 DeepSeek API key:"
  write_env  DEEPSEEK_API_KEY "$DEEPSEEK_API_KEY"
  note "这枚凭据只会进到跑 DeepSeek 那一个 Reviewer 子进程,其余子进程的环境里没有它。"
  pause
fi

# ── 5. OpenRouter 密钥 ────────────────────────────────────────────────────
stage "OpenRouter 密钥"
if have_all OPENROUTER_API_KEY; then
  skipped_stage
else
  say "第二个 Reviewer 走 OpenRouter,用一个与 DeepSeek 不同家的模型——"
  say "跨模型去重要有效,两个 Reviewer 得真的会看出不同的东西。"
  open_url "https://openrouter.ai/keys"
  step "登录后点 Create Key,填个名字(如 multireviewer)。"
  step "密钥形如 sk-or-v1-...,创建后复制。"
  ask_secret OPENROUTER_API_KEY "粘贴 OpenRouter API key:"
  write_env  OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
  note "OpenRouter 账户里要有余额,否则第一次审查会以模型调用失败告终。"
  pause
fi

# ── 6. 模型组合 ───────────────────────────────────────────────────────────
stage "模型组合"
say "写 multireviewer.config.json,它以只读方式绑进容器。"
say "模型标识同时用作 Finding 的来源标记,两个不能重名。"
note "直接回车用默认值。改模型只需改这个文件加重启,不必重新构建镜像。"

ask MULTIREVIEWER_DEEPSEEK_MODEL   "DeepSeek 模型标识 [deepseek-v4-flash]:"
ask MULTIREVIEWER_OPENROUTER_MODEL "OpenRouter 模型标识 [z-ai/glm-4.6]:"
: "${MULTIREVIEWER_DEEPSEEK_MODEL:=deepseek-v4-flash}"
: "${MULTIREVIEWER_OPENROUTER_MODEL:=z-ai/glm-4.6}"
write_env MULTIREVIEWER_DEEPSEEK_MODEL   "$MULTIREVIEWER_DEEPSEEK_MODEL"
write_env MULTIREVIEWER_OPENROUTER_MODEL "$MULTIREVIEWER_OPENROUTER_MODEL"

cat > multireviewer.config.json <<CONFIG
{
  "maxChangedLinesPerBatch": 2000,
  "reviewers": [
    {
      "provider": "deepseek",
      "model": "${MULTIREVIEWER_DEEPSEEK_MODEL}",
      "apiKeyEnv": "DEEPSEEK_API_KEY"
    },
    {
      "provider": "openrouter",
      "model": "${MULTIREVIEWER_OPENROUTER_MODEL}",
      "apiKeyEnv": "OPENROUTER_API_KEY"
    }
  ]
}
CONFIG
printf '  %s✓ 写了%s multireviewer.config.json\n' "$GREEN" "$RESET"

say "在容器里拿 Pi 内置的模型表核一遍这两个标识确实存在。"
say "标识写错时服务照样起得来,要等第一次审查跑到一半才报「模型不存在」。"
MODEL_CHECK='
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ModelRuntime } from "@earendil-works/pi-coding-agent";
const config = JSON.parse(readFileSync("/app/multireviewer.config.json", "utf8"));
const dir = mkdtempSync(join(tmpdir(), "multireviewer-check-"));
const runtime = await ModelRuntime.create({
  authPath: join(dir, "auth.json"),
  modelsPath: join(dir, "models.json"),
});
let ok = true;
for (const reviewer of config.reviewers) {
  const found = Boolean(runtime.getModel(reviewer.provider, reviewer.model));
  console.log((found ? "OK   " : "MISS ") + reviewer.provider + "/" + reviewer.model);
  if (!found) ok = false;
}
process.exit(ok ? 0 : 1);
'
MODEL_CHECK_STATUS=0
docker compose run --rm -T --entrypoint node multireviewer \
  --input-type=module -e "$MODEL_CHECK" 2>/dev/null || MODEL_CHECK_STATUS=$?
if (( MODEL_CHECK_STATUS == 0 )); then
  printf '  %s✓%s 两个模型标识都解析得到\n' "$GREEN" "$RESET"
else
  printf '  %s✗ 有标识解析不到%s\n' "$RED" "$RESET"
  say "重跑本脚本换一个标识。Pi 内置模型表里没有的标识,服务跑起来也用不了。"
  exit 1
fi
pause

# ── 7. 起服务并自检 ───────────────────────────────────────────────────────
stage "起服务并自检"
say "密钥用来校验投递签名,服务与 Gitea 两侧填同一个值。这里随机生成一枚。"

EXISTING_SECRET=$(_existing MULTIREVIEWER_WEBHOOK_SECRET || true)
if [[ -n "$EXISTING_SECRET" ]] && ! confirm "已经有一枚密钥了,重新生成?(重新生成要同步改 Gitea 那侧)"; then
  MULTIREVIEWER_WEBHOOK_SECRET="$EXISTING_SECRET"
  note "沿用现有密钥"
else
  MULTIREVIEWER_WEBHOOK_SECRET=$(openssl rand -hex 32)
  note "已生成新密钥"
fi
write_env MULTIREVIEWER_WEBHOOK_SECRET "$MULTIREVIEWER_WEBHOOK_SECRET"

say ""
say "容器内固定监听 3000,对外映射哪个端口单独设。"
note "反代到 443 时这里填反代回源的那个端口。"
ask MULTIREVIEWER_HOST_PORT "宿主机端口 [3000]:"
: "${MULTIREVIEWER_HOST_PORT:=3000}"
write_env MULTIREVIEWER_HOST_PORT "$MULTIREVIEWER_HOST_PORT"

say ""
say "Gitea 要能访问到这台服务器。填服务对外的地址。"
note "路径任意,服务不挑。"
ask MULTIREVIEWER_PUBLIC_URL "服务的公网地址(如 https://reviewer.example.com/webhook):"
write_env MULTIREVIEWER_PUBLIC_URL "$MULTIREVIEWER_PUBLIC_URL"
note "MULTIREVIEWER_PUBLIC_URL 只给这个脚本用,服务本身不读它。"

say ""
say "起服务。"
docker compose up -d
say "等它监听。"
BOOTED=""
for _ in $(seq 1 30); do
  if docker compose logs multireviewer 2>&1 | grep -q "MultiReviewer webhook 监听"; then
    BOOTED="yes"; break
  fi
  sleep 1
done
if [[ -z "$BOOTED" ]]; then
  printf '  %s✗ 没等到监听%s\n' "$RED" "$RESET"
  docker compose logs --tail 30 multireviewer
  say "上面是容器日志。Gitea 版本不够、凭据缺失都会在这里直说。"
  exit 1
fi
printf '  %s✓%s 服务已监听\n' "$GREEN" "$RESET"

say ""
say "先从本机打一个签名错误的请求,期望 401——这验容器本身。"
LOCAL_PROBE=$(curl -sS -o /dev/null -w '%{http_code}' -m 10 \
  -X POST "http://127.0.0.1:${MULTIREVIEWER_HOST_PORT}/" \
  -H 'Content-Type: application/json' -H 'X-Gitea-Event: pull_request' \
  -H 'X-Hub-Signature-256: sha256=deadbeef' -d '{}' 2>/dev/null) || LOCAL_PROBE="connect-failed"
if [[ "$LOCAL_PROBE" == "401" ]]; then
  printf '  %s✓%s 本机 401,容器与端口映射都正常\n' "$GREEN" "$RESET"
else
  printf '  %s✗ 本机回了 %s,预期 401%s\n' "$RED" "$LOCAL_PROBE" "$RESET"
  say "端口映射或容器有问题,先解决这个再谈公网。"
  exit 1
fi

# 下面这个 curl 是从本机发的,它证明不了 Gitea 到得了这个地址。地址落在只有本机认得
# 的网段时先说破:docker 网桥地址(172.17.x)尤其容易误选——本机 curl 一通就过,而
# Gitea 在别的机器上时那个地址根本不存在,投递一条也发不出来。
PUBLIC_HOST=${MULTIREVIEWER_PUBLIC_URL#*://}
PUBLIC_HOST=${PUBLIC_HOST%%[:/]*}
case "$PUBLIC_HOST" in
  localhost | 127.* | 0.0.0.0 | ::1 | 172.17.*)
    warn "$PUBLIC_HOST 只有这台机器和它上面的容器认得。"
    say "  Gitea 跑在别的机器上时,它连不到这个地址,投递会全部失败——而下面这个"
    say "  自检照样会通过,因为它是从本机发的。"
    say "  换成 Gitea 那侧访问得到的地址:本机的局域网 IP、域名、或反向代理地址。"
    say "  本机的局域网地址:$(hostname -I 2>/dev/null || echo '用 ip -4 addr 查')"
    SKIPPED+=("公网地址是 $PUBLIC_HOST,只有本机可达。以 Gitea 的投递记录为准")
    ;;
esac

say "再从公网地址打同样的请求——这验反代与防火墙。"
PROBE=$(curl -sS -o /dev/null -w '%{http_code}' -m 15 \
  -X POST "$MULTIREVIEWER_PUBLIC_URL" \
  -H 'Content-Type: application/json' -H 'X-Gitea-Event: pull_request' \
  -H 'X-Hub-Signature-256: sha256=deadbeef' -d '{}' 2>/dev/null) || PROBE="connect-failed"
case "$PROBE" in
  401)
    printf '  %s✓%s 本机到这个地址是通的\n' "$GREEN" "$RESET"
    note "这只说明本机可达。Gitea 到不到得了,只有它的投递记录说了算(下一步)。"
    ;;
  connect-failed)
    printf '  %s✗ 连不上 %s%s\n' "$RED" "$MULTIREVIEWER_PUBLIC_URL" "$RESET"
    say "容器是好的,问题在反代或防火墙。"
    SKIPPED+=("公网自检没通过,Gitea 多半也到不了这个地址") ;;
  *)
    printf '  %s⚠ 公网回了 %s,预期 401%s\n' "$YELLOW" "$PROBE" "$RESET"
    say "这个地址后面接的可能不是 MultiReviewer。确认反代指对了。"
    SKIPPED+=("公网自检回了 $PROBE 而非 401") ;;
esac
pause

# ── 8. 在 Gitea 注册 webhook ──────────────────────────────────────────────
stage "在 Gitea 注册 webhook"
if have_all MULTIREVIEWER_GITEA_REPO; then
  MULTIREVIEWER_GITEA_REPO=$(_existing MULTIREVIEWER_GITEA_REPO)
  note "$MULTIREVIEWER_GITEA_REPO 的 webhook 上一轮已经登记过,跳过。"
  note "要重新登记(换地址、换密钥)就 FORCE=1 重跑。"
else
  ask MULTIREVIEWER_GITEA_REPO "要审查的仓库(owner/repo):"
  write_env MULTIREVIEWER_GITEA_REPO "$MULTIREVIEWER_GITEA_REPO"

  HOOKS_URL="${MULTIREVIEWER_GITEA_URL%/}/${MULTIREVIEWER_GITEA_REPO}/settings/hooks"
  open_url "$HOOKS_URL"
  note "$HOOKS_URL"
  step "点「添加 Webhook」,类型选 Gitea。"
  step "目标 URL 填:$MULTIREVIEWER_PUBLIC_URL"
  step "POST Content Type 选 application/json。"
  step "密钥文本填(与服务侧同一个值):"
  printf '\n      %s%s%s\n\n' "$BOLD" "$MULTIREVIEWER_WEBHOOK_SECRET" "$RESET"
  step "触发条件选「自定义事件」,只勾 Pull Request。"
  step "勾上「激活」,保存。"
  note "组织级 webhook 也可以,一次覆盖名下全部仓库。"
  warn "密钥刚打在屏幕上了,分享终端记录前先清屏。"
  pause "保存好了吗?"

  say "在 webhook 详情页底部点「测试推送」,Gitea 会发一条投递。"
  warn "这是唯一能证明 Gitea 到得了本服务的检查。前面的自检都是从本机发的。"
  note "它发的是 push 事件,服务会回 200 但不跑审查——这一步只验连通,不验审查。"
  step "回到 Gitea 页面,展开最近一次投递,确认响应是 200。"
  note "401 是两侧密钥不一致,回上一步重填。"
  note "连接超时或拒绝,说明这个地址 Gitea 够不着,换一个它到得了的地址。"
  say ""
  say "看到 \"webhook can only call allowed HTTP servers\" 时,是 Gitea 自己拦的:"
  note "app.ini 的 [webhook] 段 ALLOWED_HOST_LIST 默认 external,只放行公网地址,"
  note "而本服务多半在私有网段。追加本服务的地址后重启 Gitea:"
  printf '\n      %s[webhook]%s\n' "$BOLD" "$RESET"
  printf '      %sALLOWED_HOST_LIST = external, %s%s\n\n' "$BOLD" "$PUBLIC_HOST" "$RESET"
  note "保留 external 使已有的其他 webhook 不受影响。别写 private——那会放开整个"
  note "RFC 1918,任何有仓库管理权的人都能把 webhook 指向内网任意服务。"
  pause
fi

# ── 9. 第一次真实审查 ─────────────────────────────────────────────────────
stage "第一次真实审查"
say "现在开一个 PR,让两个模型真的审一次。"
warn "要用一个此前没被本工具评论过的 PR。旧 PR 上留着带指纹锚点的评论,"
say "  本轮 Finding 会匹配上而被折叠进正文,看起来像一条评论都没发。"

step "在 $MULTIREVIEWER_GITEA_REPO 建一个新分支,改几十行代码,push 上去。"
step "开 PR。webhook 的 opened 事件会立刻触发一次 Review Run。"
say ""
say "盯日志:"
printf '      %sdocker compose logs -f multireviewer%s\n' "$BOLD" "$RESET"
note "一次审查按模型速度可能要几分钟。没有报错输出即在正常跑。"
say "PR 页面上应该看到:"
note "  bot 账号发的一条 review,正文是汇总,行级评论挂在具体行上。"
say "跑完之后查库(库在宿主机的 ./data 下,直接读):"
note "  sqlite3 data/multireviewer.db 'select model, cost_usd from review_run;'"
note "  sqlite3 data/multireviewer.db 'select model, count(*) from finding group by model;'"

say ""
say "没有评论出现时按这个顺序查:"
step "Gitea webhook 详情页 → 最近投递 → 响应码。401 是密钥两侧不一致。"
step "docker compose logs multireviewer。「Review Run 失败」会带上原因。"
step "模型凭据没余额、模型标识拼错,都会在日志里显形。"
pause

finish
note "部署目录 $DEPLOY_DIR,里面有 .env、multireviewer.config.json 与 data/"
note "换模型改 multireviewer.config.json,换凭据改 .env,改完 docker compose up -d"
note "更新版本:开发机上跑 scripts/build-push.sh,这里 docker compose pull && docker compose up -d"
