#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# 在**跑服务的那台服务器**上执行。服务器上不需要源码,只要这些文件放在同一个目录:
#
#   docker-compose.yml  本仓库根目录那一份,拷过来
#   setup.sh            本脚本
#   .env                由本脚本生成
#   data/               由本脚本创建,SQLite 与工作副本缓存落在这里
#
# 镜像在开发机上构建后推到 registry(`scripts/build-push.sh`),这里只负责拉取。
# 你从笔记本 SSH 进来,浏览器留在笔记本上——脚本给出的网址在笔记本上打开,把值粘回来。
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# 脚本自己所在的目录就是部署目录。在仓库里直接跑时它在 scripts/ 下,compose 文件在
# 上一级,这里一并认掉。
DEPLOY_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[[ -f "$DEPLOY_DIR/docker-compose.yml" ]] || DEPLOY_DIR="$(dirname "$DEPLOY_DIR")"
cd "$DEPLOY_DIR"
ENV_FILE="$DEPLOY_DIR/.env"

# 某个阶段要产出的值已经全在 .env 里时跳过它,重跑向导因此只补没做完的部分。
# FORCE=1 强制每个阶段都重做。
have_all() {
  if [[ -n "${FORCE:-}" ]]; then return 1; fi
  local key
  for key in "$@"; do
    [[ -n "$(_existing "$key" || true)" ]] || return 1
  done
  return 0
}

skipped_stage() {
  note "已配置,跳过。要重做就 FORCE=1 重跑本脚本。"
}

banner "MultiReviewer 部署"

# ── 1. 前置检查与镜像 ─────────────────────────────────────────────────────
stage "前置检查与镜像"

for cmd in docker curl openssl; do
  if command -v "$cmd" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$cmd"
  else
    printf '  %s✗ 缺少 %s%s\n' "$RED" "$cmd" "$RESET"; exit 1
  fi
done

if docker compose version >/dev/null 2>&1; then
  printf '  %s✓%s docker compose\n' "$GREEN" "$RESET"
else
  printf '  %s✗ 没有 docker compose 插件%s\n' "$RED" "$RESET"
  say "本脚本用的是 docker compose(v2 插件),不是独立的 docker-compose 命令。"
  exit 1
fi

if [[ ! -f docker-compose.yml ]]; then
  printf '  %s✗ 当前目录没有 docker-compose.yml%s\n' "$RED" "$RESET"
  say "把仓库根目录的 docker-compose.yml 与本脚本放到同一个目录再跑。"
  exit 1
fi
printf '  %s✓%s docker-compose.yml\n' "$GREEN" "$RESET"
note "部署目录 $DEPLOY_DIR"

say ""
say "镜像在开发机上构建并推到 registry:"
printf '      %sscripts/build-push.sh <镜像引用>%s\n' "$BOLD" "$RESET"
note "开发机是 arm64、服务器是 amd64 时,构建必须带 --platform linux/amd64,"
note "上面那个脚本已经默认这么做了。架构不对时容器起不来,报 exec format error。"

ask MULTIREVIEWER_IMAGE "镜像引用(如 registry.example.com/team/multireviewer:latest):"
write_env MULTIREVIEWER_IMAGE "$MULTIREVIEWER_IMAGE"

say "拉镜像。registry 需要登录时先 Ctrl-C,docker login 之后重跑。"
if docker compose pull; then
  printf '  %s✓%s 镜像已拉到本地\n' "$GREEN" "$RESET"
else
  printf '  %s✗ 拉取失败%s\n' "$RED" "$RESET"
  say "查:镜像引用是否拼对、是否已 docker login、镜像是否真的推上去了。"
  exit 1
fi
pause

# ── 2. 数据目录 ───────────────────────────────────────────────────────────
stage "数据目录"
say "SQLite 与工作副本缓存落在 $DEPLOY_DIR/data,绑进容器的 /data。"
note "工作副本是每个仓库一份完整 clone,磁盘占用看仓库大小。"

mkdir -p data

# 容器以当前这个宿主机用户的身份运行,新建的 data 目录天然归它所有,不必 chown。
# 部署目录在 home 下时这一点尤其重要:把它改成别的属主会让你写不进自己的 home。
MULTIREVIEWER_UID=$(id -u)
MULTIREVIEWER_GID=$(id -g)
write_env MULTIREVIEWER_UID "$MULTIREVIEWER_UID"
write_env MULTIREVIEWER_GID "$MULTIREVIEWER_GID"
note "容器将以 ${MULTIREVIEWER_UID}:${MULTIREVIEWER_GID} 运行。"

say "拿容器自己验一次这个目录写得进去。"
if docker compose run --rm -T --entrypoint sh multireviewer \
     -c 'touch /data/.probe && rm /data/.probe' >/dev/null 2>&1; then
  printf '  %s✓%s 容器写得进 /data\n' "$GREEN" "$RESET"
else
  printf '  %s✗ 容器写不进 /data%s\n' "$RED" "$RESET"
  say "多半是 $DEPLOY_DIR/data 归别人所有。执行:"
  printf '      %ssudo chown -R %s:%s %s/data%s\n' \
    "$BOLD" "$MULTIREVIEWER_UID" "$MULTIREVIEWER_GID" "$DEPLOY_DIR" "$RESET"
  exit 1
fi
pause

# ── 3. Gitea 实例与 bot 凭据 ──────────────────────────────────────────────
stage "Gitea 实例与 bot 凭据"
if have_all MULTIREVIEWER_GITEA_URL MULTIREVIEWER_GITEA_TOKEN; then
  MULTIREVIEWER_GITEA_URL=$(_existing MULTIREVIEWER_GITEA_URL)
  MULTIREVIEWER_GITEA_TOKEN=$(_existing MULTIREVIEWER_GITEA_TOKEN)
  note "凭据已配置,只做连通与版本核对。要重填就 FORCE=1 重跑。"
else
  say "审查评论以一个专用 bot 账号的身份发出。它需要:"
  step "一枚该账号签发的 PAT,scope 勾 write:repository 与 write:issue 两项,别的不要"
  say "  (实测确认的最小集合;write:issue 只为 PR 上的 👀/👍 进度 reaction)。"
  step "该账号以 **admin 权限** 加入要审查的仓库——面板注册仓库时要替你创建 webhook,"
  say "  Gitea 的 hook 管理只对仓库 admin 开放,write 不够。"
  note "这是每注册一个仓库的前置:现在至少给第一个仓库配好,之后每接入一个新仓库,"
  note "都先把 bot 提到该仓库的 admin,再去面板点注册(权限不足时注册会 403 并明说)。"
  note "签发页在 <实例地址>/user/settings/applications"

  ask        MULTIREVIEWER_GITEA_URL   "Gitea 实例根地址(如 https://gitea.example.com):"
  ask_secret MULTIREVIEWER_GITEA_TOKEN "粘贴 bot 账号的 PAT:"
  write_env  MULTIREVIEWER_GITEA_URL   "$MULTIREVIEWER_GITEA_URL"
  write_env  MULTIREVIEWER_GITEA_TOKEN "$MULTIREVIEWER_GITEA_TOKEN"
fi

say "拿这枚凭据读一次实例版本,当场验证地址与令牌。"
GITEA_VERSION=$(curl -sS -f \
  -H "Authorization: token ${MULTIREVIEWER_GITEA_TOKEN}" \
  "${MULTIREVIEWER_GITEA_URL%/}/api/v1/version" \
  | sed -E 's/.*"version" *: *"([^"]+)".*/\1/') || GITEA_VERSION=""

# 响应里没有 version 字段时 sed 会原样吐回整个 body,别把它当版本号打 ✓。
[[ "$GITEA_VERSION" =~ ^[vV]?[0-9]+(\.[0-9]+)+ ]] || GITEA_VERSION=""
if [[ -z "$GITEA_VERSION" ]]; then
  printf '  %s✗ 读不到版本%s\n' "$RED" "$RESET"
  say "地址不对、令牌无效、或实例不允许这枚令牌调用 API。三者都查一遍再重跑。"
  say "这台服务器也可能根本访问不到 Gitea——先 curl 一下实例地址确认网络通。"
  exit 1
fi
printf '  %s✓%s 实例版本 %s\n' "$GREEN" "$RESET" "$GITEA_VERSION"
note "下限:社区版 1.26.0 / 企业版 26.0.0。Disposition 依赖的 resolve 端点自该版本才有。"
note "服务启动时会再检查一次,不合格会直接退出。"
pause

# ── 4. DeepSeek 密钥 ──────────────────────────────────────────────────────
stage "DeepSeek 密钥"
if have_all DEEPSEEK_API_KEY; then
  skipped_stage
else
  say "第一个 Reviewer 走 DeepSeek 官方接口。"
  open_url "https://platform.deepseek.com/api_keys"
  step "登录后进 API keys 页,点「创建 API key」。"
  step "密钥只在创建那一刻完整显示一次,当场复制。"
  ask_secret DEEPSEEK_API_KEY "粘贴 DeepSeek API key:"
  write_env  DEEPSEEK_API_KEY "$DEEPSEEK_API_KEY"
  note "这枚凭据只会进到跑 DeepSeek 那一个 Reviewer 子进程,其余子进程的环境里没有它。"
  pause
fi

# ── 5. OpenRouter 密钥 ────────────────────────────────────────────────────
stage "OpenRouter 密钥"
if have_all OPENROUTER_API_KEY; then
  skipped_stage
else
  say "第二个 Reviewer 走 OpenRouter,用一个与 DeepSeek 不同家的模型——"
  say "跨模型去重要有效,两个 Reviewer 得真的会看出不同的东西。"
  open_url "https://openrouter.ai/keys"
  step "登录后点 Create Key,填个名字(如 multireviewer)。"
  step "密钥形如 sk-or-v1-...,创建后复制。"
  ask_secret OPENROUTER_API_KEY "粘贴 OpenRouter API key:"
  write_env  OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
  note "OpenRouter 账户里要有余额,否则第一次审查会以模型调用失败告终。"
  pause
fi

# ── 6. 模型组合 ───────────────────────────────────────────────────────────
stage "模型组合"
say "模型组合在库里,由面板的设置页管。这一步先把两个标识核准,记进 .env 备查。"
say "模型标识同时用作 Finding 的来源标记,两个不能重名。"
note "直接回车用默认值。"

ask MULTIREVIEWER_DEEPSEEK_MODEL   "DeepSeek 模型标识 [deepseek-v4-flash]:"
ask MULTIREVIEWER_OPENROUTER_MODEL "OpenRouter 模型标识 [z-ai/glm-4.6]:"
: "${MULTIREVIEWER_DEEPSEEK_MODEL:=deepseek-v4-flash}"
: "${MULTIREVIEWER_OPENROUTER_MODEL:=z-ai/glm-4.6}"
write_env MULTIREVIEWER_DEEPSEEK_MODEL   "$MULTIREVIEWER_DEEPSEEK_MODEL"
write_env MULTIREVIEWER_OPENROUTER_MODEL "$MULTIREVIEWER_OPENROUTER_MODEL"

say "在容器里拿 Pi 内置的模型表核一遍这两个标识确实存在。"
say "标识写错时服务照样起得来,要等第一次审查跑到一半才报「模型不存在」。"
MODEL_CHECK='
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ModelRuntime } from "@earendil-works/pi-coding-agent";
const reviewers = [
  { provider: "deepseek", model: process.env.CHECK_DEEPSEEK_MODEL },
  { provider: "openrouter", model: process.env.CHECK_OPENROUTER_MODEL },
];
const dir = mkdtempSync(join(tmpdir(), "multireviewer-check-"));
const runtime = await ModelRuntime.create({
  authPath: join(dir, "auth.json"),
  modelsPath: join(dir, "models.json"),
});
let ok = true;
for (const reviewer of reviewers) {
  const found = Boolean(runtime.getModel(reviewer.provider, reviewer.model));
  console.log((found ? "OK   " : "MISS ") + reviewer.provider + "/" + reviewer.model);
  if (!found) ok = false;
}
process.exit(ok ? 0 : 1);
'
MODEL_CHECK_STATUS=0
docker compose run --rm -T --entrypoint node \
  -e "CHECK_DEEPSEEK_MODEL=$MULTIREVIEWER_DEEPSEEK_MODEL" \
  -e "CHECK_OPENROUTER_MODEL=$MULTIREVIEWER_OPENROUTER_MODEL" \
  multireviewer --input-type=module -e "$MODEL_CHECK" 2>/dev/null || MODEL_CHECK_STATUS=$?
if (( MODEL_CHECK_STATUS == 0 )); then
  printf '  %s✓%s 两个模型标识都解析得到\n' "$GREEN" "$RESET"
else
  printf '  %s✗ 有标识解析不到%s\n' "$RED" "$RESET"
  say "重跑本脚本换一个标识。Pi 内置模型表里没有的标识,服务跑起来也用不了。"
  exit 1
fi
pause

# ── 7. 面板凭据与基地址 ───────────────────────────────────────────────────
stage "面板凭据与基地址"

# 旧的全局 secret 流程(issue #28 之前)留下的变量,检出即清:服务已经不读它们,
# 留着只会误导下一个看 .env 的人以为它们还在生效。
remove_env() {
  local key="$1" reason="$2"
  [[ -f "$ENV_FILE" ]] || return 0
  grep -qE "^${key}=" "$ENV_FILE" || return 0
  local tmp; tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  mv "$tmp" "$ENV_FILE"
  printf '  %s✓ 清掉旧变量%s %s\n' "$GREEN" "$RESET" "$key"
  note "  $reason"
}
OLD_SECRET=$(_existing MULTIREVIEWER_WEBHOOK_SECRET || true)
remove_env MULTIREVIEWER_WEBHOOK_SECRET "全局 webhook secret 已废除:准入改为每仓库一把 Key,由面板在注册时生成并写进 hook。"
remove_env MULTIREVIEWER_PUBLIC_URL "公网地址改为基地址,存 MULTIREVIEWER_BASE_URL(下面会问)。"
remove_env MULTIREVIEWER_GITEA_REPO "webhook 不再手工登记:仓库改在面板上注册。"
if [[ -n "$OLD_SECRET" ]]; then
  warn "Gitea 上手工建过的旧 webhook 用的是刚清掉的全局 secret,已经验不过签名。"
  say "  到各仓库的 设置 → Web 钩子 删掉指向本服务的旧 hook,改由面板注册时自动创建。"
fi

say "面板登录用一枚 admin token。这里随机生成,登录页粘贴它。"
EXISTING_TOKEN=$(_existing MULTIREVIEWER_ADMIN_TOKEN || true)
if [[ -n "$EXISTING_TOKEN" ]] && ! confirm "已经有 admin token 了,重新生成?(重新生成后旧 token 立即失效)"; then
  MULTIREVIEWER_ADMIN_TOKEN="$EXISTING_TOKEN"
  note "沿用现有 token"
else
  MULTIREVIEWER_ADMIN_TOKEN=$(openssl rand -hex 32)
  note "已生成新 token"
fi
write_env MULTIREVIEWER_ADMIN_TOKEN "$MULTIREVIEWER_ADMIN_TOKEN"

say ""
say "面板挂在一段不可猜的路径前缀下(如 /panel-3f2a),webhook 与它互不相扰。"
EXISTING_PREFIX=$(_existing MULTIREVIEWER_PANEL_PREFIX || true)
if [[ -n "$EXISTING_PREFIX" ]] && ! confirm "已经有前缀 /$EXISTING_PREFIX 了,重新生成?(重新生成后旧地址失效,书签要更新)"; then
  MULTIREVIEWER_PANEL_PREFIX="$EXISTING_PREFIX"
  note "沿用现有前缀"
else
  MULTIREVIEWER_PANEL_PREFIX="panel-$(openssl rand -hex 4)"
  note "已生成前缀 /$MULTIREVIEWER_PANEL_PREFIX"
fi
write_env MULTIREVIEWER_PANEL_PREFIX "$MULTIREVIEWER_PANEL_PREFIX"

say ""
say "容器内固定监听 3000,对外映射哪个端口单独设。"
note "反代到 443 时这里填反代回源的那个端口。"
ask MULTIREVIEWER_HOST_PORT "宿主机端口 [3000]:"
: "${MULTIREVIEWER_HOST_PORT:=3000}"
write_env MULTIREVIEWER_HOST_PORT "$MULTIREVIEWER_HOST_PORT"

say ""
say "服务对外的基地址:Gitea 的投递、浏览器里的面板都走它。不带路径,"
say "hook 地址与面板地址都由服务自己在它后面拼。"
ask MULTIREVIEWER_BASE_URL "基地址(如 https://reviewer.example.com):"
MULTIREVIEWER_BASE_URL="${MULTIREVIEWER_BASE_URL%/}"
# 旧流程的习惯是填 <地址>/webhook,现在只要基地址,顺手剥掉。
if [[ "$MULTIREVIEWER_BASE_URL" == */webhook ]]; then
  MULTIREVIEWER_BASE_URL="${MULTIREVIEWER_BASE_URL%/webhook}"
  note "剥掉了 /webhook 后缀,基地址不带路径:$MULTIREVIEWER_BASE_URL"
fi
# 先校验再落盘:坏值写进 .env 会在重跑时被 ask 当默认值回填。判定与服务端
# (src/main.ts)对齐——host 精确等于 localhost / 127.0.0.1 / [::1] 才放行明文,
# 前缀 glob 会放过 localhost.evil.com 这类域名。
case "$MULTIREVIEWER_BASE_URL" in
  https://*) ;;
  http://*)
    BASE_HOST=${MULTIREVIEWER_BASE_URL#http://}
    BASE_HOST=${BASE_HOST%%/*}
    case "$BASE_HOST" in
      localhost | localhost:* | 127.0.0.1 | 127.0.0.1:* | "[::1]" | "[::1]:"*) ;;
      *)
        printf '  %s✗ 明文 http 且不是 localhost:%s%s\n' "$RED" "$MULTIREVIEWER_BASE_URL" "$RESET"
        say "admin token 和 cookie 会在网络上裸奔,服务启动时会直接拒绝。换 https 再来。"
        exit 1 ;;
    esac ;;
  *)
    printf '  %s✗ 基地址要以 http:// 或 https:// 开头:%s%s\n' "$RED" "$MULTIREVIEWER_BASE_URL" "$RESET"
    exit 1 ;;
esac
write_env MULTIREVIEWER_BASE_URL "$MULTIREVIEWER_BASE_URL"
pause

# ── 8. 起服务并自检 ───────────────────────────────────────────────────────
stage "起服务并自检"
say "起服务。"
docker compose up -d
say "等它监听。"
BOOTED=""
for _ in $(seq 1 30); do
  if docker compose logs multireviewer 2>&1 | grep -q "MultiReviewer webhook 监听"; then
    BOOTED="yes"; break
  fi
  sleep 1
done
if [[ -z "$BOOTED" ]]; then
  printf '  %s✗ 没等到监听%s\n' "$RED" "$RESET"
  docker compose logs --tail 30 multireviewer
  say "上面是容器日志。Gitea 版本不够、凭据缺失都会在这里直说。"
  exit 1
fi
printf '  %s✓%s 服务已监听\n' "$GREEN" "$RESET"

PANEL_PATH="/${MULTIREVIEWER_PANEL_PREFIX}/"
LOCAL_PANEL="http://127.0.0.1:${MULTIREVIEWER_HOST_PORT}${PANEL_PATH}"

say ""
say "自检收在「面板能登录」:先从本机打登录页,期望 200——这验容器、端口映射与前端产物。"
LOCAL_PROBE=$(curl -sS -o /dev/null -w '%{http_code}' -m 10 "${LOCAL_PANEL}login" 2>/dev/null) \
  || LOCAL_PROBE="connect-failed"
if [[ "$LOCAL_PROBE" == "200" ]]; then
  printf '  %s✓%s 本机登录页 200\n' "$GREEN" "$RESET"
else
  printf '  %s✗ 本机登录页回了 %s,预期 200%s\n' "$RED" "$LOCAL_PROBE" "$RESET"
  say "503 是镜像里缺前端产物(dist),404 是前缀对不上,连不上是端口映射。"
  say "都属于容器与镜像的问题,先解决这个再谈公网。"
  exit 1
fi

say "再用刚写进 .env 的 token 真登录一次,期望 204 加 Set-Cookie——这验 token 没写坏。"
LOGIN_HEADERS=$(curl -sS -D - -o /dev/null -m 10 \
  -X POST "${LOCAL_PANEL}api/session" \
  -H 'Content-Type: application/json' \
  -d "{\"token\":\"${MULTIREVIEWER_ADMIN_TOKEN}\"}" 2>/dev/null) || LOGIN_HEADERS=""
if printf '%s' "$LOGIN_HEADERS" | head -1 | grep -q ' 204' \
  && printf '%s' "$LOGIN_HEADERS" | grep -qi '^set-cookie:'; then
  printf '  %s✓%s 登录成功,拿到会话 cookie\n' "$GREEN" "$RESET"
else
  printf '  %s✗ 登录失败%s\n' "$RED" "$RESET"
  if printf '%s' "$LOGIN_HEADERS" | head -1 | grep -q ' 429'; then
    say "429:此前失败太多次触发了按 IP 的退避锁定。等几分钟再重跑,别连续硬试。"
  else
    say "服务在跑但 token 对不上——.env 里的值与容器读到的值不一致(改了 .env 没重启,"
    say "或值里混进了引号/空白)。修好前不算部署完成:"
    printf '      %sdocker compose up -d && FORCE=1 重跑本脚本%s\n' "$BOLD" "$RESET"
  fi
  exit 1
fi

# 下面这个 curl 是从本机发的,它证明不了 Gitea 或你的浏览器到得了这个地址。地址落在
# 只有本机认得的网段时先说破:docker 网桥地址(172.17.x)尤其容易误选——本机 curl 一
# 通就过,而 Gitea 在别的机器上时那个地址根本不存在,投递一条也发不出来。
PUBLIC_HOST=${MULTIREVIEWER_BASE_URL#*://}
PUBLIC_HOST=${PUBLIC_HOST%%[:/]*}
case "$PUBLIC_HOST" in
  localhost | 127.* | 0.0.0.0 | ::1 | 172.17.*)
    warn "$PUBLIC_HOST 只有这台机器和它上面的容器认得。"
    say "  Gitea 与你的浏览器在别的机器上时,它们连不到这个地址——而下面这个自检"
    say "  照样会通过,因为它是从本机发的。"
    say "  换成两侧都访问得到的地址:本机的局域网 IP、域名、或反向代理地址。"
    say "  本机的局域网地址:$(hostname -I 2>/dev/null || echo '用 ip -4 addr 查')"
    SKIPPED+=("基地址是 $PUBLIC_HOST,只有本机可达。以浏览器真开一次面板为准")
    ;;
esac

say "再从基地址打一次登录页——这验反代与防火墙。"
PROBE=$(curl -sS -o /dev/null -w '%{http_code}' -m 15 \
  "${MULTIREVIEWER_BASE_URL}${PANEL_PATH}login" 2>/dev/null) || PROBE="connect-failed"
case "$PROBE" in
  200)
    printf '  %s✓%s 本机经基地址到面板是通的\n' "$GREEN" "$RESET"
    note "这只说明本机可达。你的浏览器到不到得了,交付清单里让你真开一次。"
    ;;
  connect-failed)
    printf '  %s✗ 连不上 %s%s\n' "$RED" "${MULTIREVIEWER_BASE_URL}${PANEL_PATH}" "$RESET"
    say "容器是好的,问题在反代或防火墙。"
    SKIPPED+=("公网自检没通过,浏览器与 Gitea 多半也到不了这个地址") ;;
  *)
    printf '  %s⚠ 基地址回了 %s,预期 200%s\n' "$YELLOW" "$PROBE" "$RESET"
    say "这个地址后面接的可能不是 MultiReviewer,或反代吃掉了 /${MULTIREVIEWER_PANEL_PREFIX} 路径。"
    SKIPPED+=("公网自检回了 $PROBE 而非 200") ;;
esac
pause

# ── 9. 交付清单 ───────────────────────────────────────────────────────────
stage "交付清单"
say "部署边界到「面板能登录」为止。仓库接入、key 轮转、模型覆盖都在面板上做。"
say ""
say "面板地址(在你自己的浏览器上开):"
printf '\n      %s%s%s%s\n\n' "$BOLD" "$MULTIREVIEWER_BASE_URL" "$PANEL_PATH" "$RESET"
say "admin token(登录页粘贴;也存在 $ENV_FILE 的 MULTIREVIEWER_ADMIN_TOKEN):"
printf '\n      %s%s%s\n\n' "$BOLD" "$MULTIREVIEWER_ADMIN_TOKEN" "$RESET"
warn "token 刚打在屏幕上了,分享终端记录前先清屏。"
say ""
say "下一步,都在面板里:"
step "浏览器开上面的地址,粘 token 登录。"
step "仓库页点「注册」,填 owner/repo——面板会验 bot 权限、生成 Key、创建 webhook,"
say "  一步到位。前置:bot 在该仓库是 admin(阶段 3 说过,每个仓库都要)。"
step "注册完开一个 PR,第一轮审查自动触发;评审记录页能看到它。"
note "要用一个此前没被本工具评论过的 PR:旧 PR 上留着指纹锚点,Finding 会被折叠进正文。"
pause

finish
note "部署目录 $DEPLOY_DIR,里面有 .env 与 data/"
note "换模型在面板的设置页改,改完即时生效,不必重启"
note "更新版本:开发机上跑 scripts/build-push.sh,这里 docker compose pull && docker compose up -d"
printf '\n'
say "服务器侧排障速查:"
note "  面板打不开 → docker compose logs multireviewer;503 是镜像缺前端产物,404 查前缀。"
note "  登录 401 → .env 的 token 与容器不一致,改完要 docker compose up -d 重启。"
note "  注册 403 → bot 不是该仓库 admin。"
note "  投递没反应 → Gitea 仓库 设置 → Web 钩子 → 最近投递的响应码;401 时:仓库没注册就先注册,注册过的到面板点「轮转推平」。"
note "  Gitea 拦投递(allowed HTTP servers)→ app.ini [webhook] ALLOWED_HOST_LIST = external, ${PUBLIC_HOST}"
note "  审查失败 → docker compose logs 里「Review Run 失败」带原因;模型没余额、标识拼错都在这。"
note "  查库 → sqlite3 data/multireviewer.db 'select model, count(*) from finding group by model;'"
